config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'search', to: 'posts#search'
  resources :posts do
    collection do
      get  'set_category_children',      defaults: { format: 'json' }
    end
  end
  resources :comments, only: %i[create destroy]
  resources :users, only: %i[show edit update]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  } 
  
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :bigint           not null, primary key
#  body            :text(65535)
#  child_category  :string(255)
#  parent_category :string(255)
#  title           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :integer
#

class Post < ApplicationRecord
  has_many :comments, dependent: :delete_all
  has_many :post_tag_relations, dependent: :delete_all
  has_many :tags, through: :post_tag_relations
  belongs_to :user

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :parent_category, presence: true
  validates :child_category, presence: true

  has_many_attached :images
  validates :images, presence: true, blob: {
    content_type: ['image/png', 'image/jpg', 'image/jpeg'],
    size_range: 1..5.megabytes
  }

  scope :recent, -> { order(created_at: :desc) }
  scope :user, ->(user_id) { where(user_id: user_id) }
  scope :category, ->(params) { where(child_category: params) }

  def self.user_posts_search(post_user_id, post_id)
    with_attached_images.recent.user(post_user_id).where.not(id: post_id)
  end

  def self.new_posts_search(post_id, post_user_id)
    with_attached_images.recent.where.not(id: post_id, user_id: post_user_id)
  end

  def save_tags(tag_list)
    tag_list.each do |tag|
      find_tag = Tag.find_by(tag_name: tag.downcase)
      if find_tag
        PostTagRelation.create!(post_id: id, tag_id: find_tag.id)
      else
        begin
          tags.create!(tag_name: tag)
        rescue StandardError
          nil
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_target_post, only: %i[show edit update destroy]
  before_action :set_parent_category_array, only: %i[new edit create update]
  before_action :set_child_category_array, only: %i[edit update]
  before_action :set_images_count, only: %i[edit update]
  before_action :set_tags, only: %i[edit]

  def index
    @category_parent_array = ['犬種で絞り込み']
    Category.parent_name_set(@category_parent_array)

    @category_child_array = []
    if @q.child_category_eq
      @category_child_array = Category.child_name_set(@category_child_array, @q)
    end

    @params = params[:q][:child_category_eq] if params[:q]
    @posts = params[:q].present? ? Post.category(@params) : Post.all
    @posts = @posts.with_attached_images.recent.page(params[:page])
  end

  def search
    @q = Post.search(search_params)
    @posts_length = @q.result.length
    @posts = @q.result.with_attached_images.recent.page(params[:page])
  end

  def new
    @post = Post.new
    set_images_count
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      tag_list = tag_params[:tag_names].gsub(/[[:space:]]/, '').split(',').uniq
      @post.save_tags(tag_list)
      flash[:notice] = "「#{@post.title}」を新規投稿しました"
      redirect_to @post
    else
      set_child_category_array
      set_images_count
      @tags = tag_params[:tag_names].gsub(/[[:space:]]/, '').split(',').uniq
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      @post.tags.clear
      tag_list = tag_params[:tag_names].gsub(/[[:space:]]/, '').split(',').uniq
      @post.save_tags(tag_list)
      delete_images if params[:post][:images_blob_ids]
      flash[:notice] = "「#{@post.title}」を更新しました"
      redirect_to @post
    else
      @tags = tag_params[:tag_names].gsub(/[[:space:]]/, '').split(',').uniq
      render :edit
    end
  end

  def show
    @comment = Comment.new(post_id: @post.id)
    @comments = @post.comments.includes(user: { image_attachment: :blob })
    @user_posts = Post.user_posts_search(@post.user.id, @post.id).limit(3)
    @new_posts = Post.new_posts_search(@post.id, @post.user.id).limit(3)
  end

  def destroy
    if @post.user.id == current_user.id
      @post.destroy
      redirect_to posts_path, flash: { alert: "「#{@post.title}」を削除しました" }
    else
      redirect_to posts_path, flash: { alert: '記事を削除できませんでした' }
    end
  end

  def set_category_children
    @category_children = Category.find_by(
      name: params[:parent_name].to_s,
      ancestry: nil
    ).children
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :parent_category,
      :child_category,
      images: []
    ).merge(user_id: current_user.id)
  end

  def set_target_post
    @post = Post.with_attached_images.find(params[:id])
  end

  def delete_images
    params[:post][:images_blob_ids].each do |image_id|
      image = @post.images.find(image_id)
      image.purge
    end
  end

  def search_params
    params.require(:q).permit(:title_cont)
  end

  def tag_params
    params.require(:post).permit(:tag_names)
  end

  def set_parent_category_array
    @category_parent_array = ['---']
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end

  def set_child_category_array
    @category_child_array = [{ id: '---', name: '---' }]
    @parent = Category.find_by(name: @post.parent_category)
    @parent&.children&.each do |child|
      @category_child_array += [{ id: child.id, name: child.name }]
    end
  end

  def set_images_count
    @images_count = @post.images.length.to_i
  end

  def set_tags
    @tags = []
    @post.tags.each do |tag|
      @tags << tag.tag_name
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.haml
.p-comment__formBox
  %p.p-comment__formTitle コメント記入
  = form_for comment do |f|
    = f.hidden_field :post_id
    .form-group
      = f.label :comment, 'コメント'
      = f.text_area :comment, class: 'form-control', rows: 4
    = f.submit '送信', class: 'btn btn-primary'

app/views/posts/_form.html.haml
= render 'shared/error_messages'

= form_with model: post, local: true, id: 'posts_form' do |f|
  .form-group#post-images-area
    = f.label :images, '画像（1枚〜6枚まで）：'
    = f.file_field :images, multiple: true, class: 'image-upload-btn', id: "post_images_#{@images_count + 1}"
  .form-group.image-boxes
    - post.images.each_with_index do |image, index|
      .image-box.m-3.float-left{ id: "image-box-#{index + 1}" }
        = image_tag image, class: "mb-1 image-box__image"
        .delete-btn{ id: "delete-btn-#{index + 1}" }= icon('far', 'times-circle')
      .delete-check-boxes
        = f.check_box :images_blob_ids, { multiple: true, checked: false, class: "check-box-#{index + 1}" }, image.id, false
    = f.label :images, "+", class: "add_image text-center m-3 float-left", id: "have_#{@images_count}_img", for: "post_images_#{@images_count + 1}"
  .form-row
    .col-md-8
      .form-group
        = f.label :title, 'タイトル（50文字以内）：'
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body, '本文（1000文字以内）：'
        = f.text_area :body, class: 'form-control', rows: 12
    .col-md-4
      .form-group#category
        = f.label :parent_category, '犬種：'
        = f.select :parent_category, @category_parent_array, {}, { id: 'parent_category', class: 'form-control' } 
        - if @category_child_array
          = f.select :child_category, options_for_select(@category_child_array.map{ |c|[c[:name], c[:name], { data: { category: c[:id] } }] }, @post.child_category), {}, { id: 'child_category', class: "form-control mt-2" }
      .form-group
        = f.label :tag_names, 'タグ（カンマ区切り）：'
        - if tags
          = f.text_field :tag_names, class: 'form-control', value: tags.join(",")
        - else
          = f.text_field :tag_names, class: 'form-control'

  = f.submit '保存', class: 'btn btn-primary mt-3'

app/views/posts/_post.html.haml
.card
  .card-header
    %ul.show-post__info.list-inline
      %li.list-inline-item
        = link_to user_path(post.user.id) do
          - if post.user.image.attached?
            = image_tag post.user.image, class: 'mr-1'
          - else
            = image_tag 'no_image.png', class: 'mr-1'
          = post.user.name
      - if post.created_at == post.updated_at
        %li.list-inline-item
          = icon("far", "clock")
          = "#{post.created_at.to_s(:datetime_day_jp)}に投稿"
      - else
        %li.list-inline-item
          = icon("far", "edit")
          = "#{post.updated_at.to_s(:datetime_day_jp)}に更新"
      - if user_signed_in? && current_user.id == post.user.id
        %li.list-inline-item.float-right.dropdown
          %span{ role: "button", id: "dropdownMenu", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "true" } }= icon("fas", "ellipsis-h")
          .dropdown-menu.dropdown-menu-right{ aria: { labelledby: "dropdownMenu" } }
            = link_to '編集する', edit_post_path(post), class: 'dropdown-item'
            = link_to '削除する', post_path, class: 'dropdown-item text-danger', method: :delete, data: { confirm: '本当に削除しますか？' }
    %h4
      = post.title
    %span.badge.badge-info
      = post.parent_category
    %span.badge.badge-info
      = post.child_category
    - post.tags.each do |tag|
      %span.badge.badge-info
        = tag.tag_name
  .card-body
    %ul.slider-pc.d-none.d-md-block
      - if post.images.attached?
        - post.images.each do |image|
          %li
            = image_tag image, class: 'show-post__images--pc'
    %ul.slider-sp.d-block.d-md-none
      - if post.images.attached?
        - post.images.each do |image|
          %li
            = image_tag image, class: 'show-post__images--sp'
  .card-body
    %p.card-text
      = simple_format(post.body)
  

app/views/posts/_posts.html.haml
- posts.each do |post|
  .col-md-4.post-list__items__item
    = link_to post do
      - if post.images.attached?
        - post.images.first(1).each do |image|
          = image_tag image, class: 'post-list__items__item__image'
      - else
        = image_tag 'no_image.png', class: "post-list__items__item__image"
      .post-list__items__item__text
        = post.title

app/views/posts/edit.html.haml
- content_for(:html_title) {'編集 | BowWow!'}

.container.new-post
  .d-flex.align-items-center.new-post__upper
    %h1 編集
    .ml-auto.boards__linkBox
      = link_to '戻る', post_path, class: 'btn btn-outline-dark'

  = render partial: 'form', locals: { post: @post, tags: @tags }

app/views/posts/index.html.haml
- content_for(:html_title) {'みんなの投稿 | BowWow!'}

.container.post-list
  %h1.text-center.font-weight-bold みんなの投稿
  = render 'layouts/flashes'
  .ml-auto.post-list__linkBox.text-right
    = search_form_for(@q, url: posts_path, id: "search_category") do |f|
      - if @q.child_category_eq
        = link_to 'リセット', root_path, class: "btn-outline-dark"
      = f.select :parent_category_eq, @category_parent_array, {}, { id: 'search_parent_category', class: 'form-control post-list__select mb-2' }
      - if @q.child_category_eq
        = f.select :child_category_eq, options_for_select(@category_child_array.map{|c|[c[:name], c[:name], {'data-category' => c[:id]}]}, @q.child_category_eq), {}, { id: 'search_child_category', class: 'form-control post-list__select mb-2', onchange: 'submit(this.form);' }

  - if @posts.length == 0
    %h3.text-center.mt-5
      そのイッヌはまだここにはいません(T_T)
  - else
    .row.post-list__items
      = render partial: 'posts', locals: { posts: @posts }

  = paginate @posts

- if user_signed_in?
  .d-none.d-md-block
    = link_to icon("fas", "plus-circle") + ' 新規投稿', new_post_path, class: 'new-post-btn--pc', id: 'new-post-btn'
  .d-block.d-md-none
    = link_to icon("fas", "plus"), new_post_path, class: 'new-post-btn--sp'

app/views/posts/new.html.haml
- content_for(:html_title) {'新規投稿 | BowWow!'}

.container.new-post
  .d-flex.align-items-center.new-post__upper
    %h1 新規投稿
    .ml-auto.boards__linkBox
      = link_to '投稿一覧', root_path, class: 'btn btn-outline-dark'

  = render partial: 'form', locals: { post: @post, tags: @tags }

app/views/posts/search.html.haml
- content_for(:html_title) {'検索結果 | BowWow!'}

.container.post-list
  %h1.text-center
    = "検索結果：#{@posts_length}件"
  = render 'layouts/flashes'
  .row.post-list__items
    = render partial: 'posts', locals: { posts: @posts }

  = paginate @posts

- if user_signed_in?
  .d-none.d-md-block
    = link_to icon("fas", "plus-circle") + ' 新規投稿', new_post_path, class: 'new-post-btn--pc'
  .d-block.d-md-none
    = link_to icon("fas", "plus"), new_post_path, class: 'new-post-btn--sp'

app/views/posts/show.html.haml
- content_for(:html_title) {"#{@post.title} | BowWow!"}

.container.show-post
  - if flash[:notice]
    .alert.alert-primary
      = flash[:notice]
  - if flash[:alert]
    .alert.alert-danger
      = flash[:alert]
  .row
    .col-md-8
      = render @post

      - if user_signed_in?
        = render partial: 'comments/form', locals: { comment: @comment }
      .p-comment__list
        .p-comment__listTitle コメント
        = render partial: 'comments/comment', locals: { comments: @comments }

    .col-md-4
      .card
        .card-header
          %h6
            = link_to user_path(@post.user.id) do
              = @post.user.name + "さん"
            = "のその他の投稿"
        .card-body
          .post-list__items
            - if @user_posts.length == 0
              %p その他の投稿はありません
            - else
              = render partial: 'shared/side_column', locals: { posts: @user_posts }
      .card.mt-4
        .card-header
          %h6 新着投稿
        .card-body
          .post-list__items
            = render partial: 'shared/side_column', locals: { posts: @new_posts }