config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  get 'search', to: 'posts#search'
  resources :posts do
    collection do
      get  'set_category_children',      defaults: { format: 'json' }
    end
  end
  resources :comments, only: %i[create destroy]
  resources :users, only: %i[show edit update]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
  } 
  
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_ransack

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def set_ransack
    @q = Post.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << ' active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/views/application/_footer.html.haml
%footer.footer
  %p.footer__item &copy; 2020 BowWow!

app/views/application/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.sticky-top
  = link_to root_path, class: 'navbar-brand' do
    = image_tag 'bow-wow-logo.png', class: 'navbar-logo'
  %button.navbar-toggler{ type: "button", 
                          data: { toggle: "collapse", target: "#navbarSupportedContent" },
                          aria: { controls: "navbarSupportedContent", expanded: "false", label: "Toggle navigation" } }
    %span.navbar-toggler-icon

  .collapse.navbar-collapse#navbarSupportedContent
    %ul.navbar-nav.mr-auto
      - if user_signed_in?
        %li.nav-item.pl-1
          = header_link_item(icon('fas', 'th') + " 投稿一覧", root_path)
        %li.nav-item.pl-1
          = header_link_item(icon('fas', 'plus-circle') + " 新規投稿", new_post_path)
        %li.nav-item.pl-1.dropdown
          = link_to icon('fas', 'user') + " #{current_user.name}さん", "#", class: "nav-link dropdown-toggle", id: "navbarDropdown", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" }
          .dropdown-menu{ aria: { labelledby: "navbarDropdown" } }
            = link_to 'マイページ', user_path(current_user), class: 'dropdown-item'
            = link_to 'ログアウト', logout_path, class: 'dropdown-item'
      - else
        %li.nav-item.pl-1
          = header_link_item(icon('fas', 'th') + " 投稿一覧", root_path)
        %li.nav-item.pl-1
          = header_link_item(icon('fas', 'user-plus') + " ユーザー登録", signup_path)
        %li.nav-item.pl-1
          = header_link_item(icon('fas', 'sign-in-alt') + " ログイン", login_path)

    = search_form_for(@q, url: search_path, class: "form-inline my-2 my-lg-0") do |f|
      = f.search_field :title_cont, class:"form-control mr-sm-2", type: "search", placeholder: "Search", area: { label: "Search" }
      = f.submit 'Search', class: "btn btn-outline-success my-2 my-sm-0", type: "submit"